name: Build and Validate
on:
  schedule:
    - cron: 16 10 * * 3
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with:
          args: assemble

  dependency-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Dependency Check
        uses: hypertrace/github-actions/dependency-check@main
